name: 'Setup docker buildx'
description: 'Setup docker buildx'

inputs:
  DOCKER_ACCESS_TOKEN:
    description: 'DOCKER_ACCESS_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: mrskul
        password: '${{ inputs.DOCKER_ACCESS_TOKEN }}'
